### ISSUE TITLE
Enable number buttons for taking input

### ISSUE THREAD

**Issue by Apoorve73** [Apoorve73/racefor100.github.io#1]
Currently! **Number buttons are not responsive for input** . Enable them in such a way that whatever button is clicked, the input in the prompt take that number as input.

**Comment by maaz-bin-asad** [comment]
> Currently! **Number buttons are not responsive for input** . Enable them in such a way that whatever button is clicked, the input in the prompt take that number as input.

Assign me this issue

**Comment by Apoorve73** [comment]
I hope you will fix it soon. Wish you all the best! 👍

**Comment by prasoonjain006** [comment]
@Apoorve73  may I work on this issue ?

**Comment by Apoorve73** [comment]
Yes, @prasoonjain006 ! You have done a good job in the previous issues. I will be happy assigning it to you too!!

**Comment by Apoorve73** [comment]
Do pull the changes first!
