### ISSUE TITLE
Disable/Hide the button once the game is started

### ISSUE THREAD

**Issue by HashirGJ8842** [Apoorve73/racefor100.github.io#19]
Currently the play button persists even if the game has begun. This is unnecessary when the game is begun.

**Comment by Apoorve73** [comment]
Thank you @HashirGJ8842 . Would you like to work on it?

**Comment by HashirGJ8842** [comment]
Go ahead, if you wish, you can assign it to me👍.

**Comment by Apoorve73** [comment]
All the best :+1:
