### ISSUE TITLE
display final scoreboard

### ISSUE THREAD

**Issue by prasoonjain006** [Apoorve73/racefor100.github.io#23]
Display scoreboard till the sum reaches 100.

**Comment by Apoorve73** [comment]
Which kind of scoreboard you would like to add?

**Comment by prasoonjain006** [comment]
@Apoorve73  Currently, scoreboard does not display scores for the last guess. This scoreboard should also display the final sum.

**Comment by Apoorve73** [comment]
That's better. Would you like to fix it?

**Comment by prasoonjain006** [comment]
Assign me @Apoorve73
