### ISSUE TITLE
Number 100 Bug

### ISSUE THREAD

**Issue by prasoonjain006** [Apoorve73/racefor100.github.io#3]
Anyone can win the game by entering **number 100** two times .

**Comment by Apoorve73** [comment]
Thank you @prasoonjain006 for finding this bug. There may be some callback issues. Would you like to work on it?

**Comment by prasoonjain006** [comment]
yes I can try

**Comment by Apoorve73** [comment]
I am assigning you the issue. Hope you find the solution soon !
Wish you Good Luck!
