### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by Apoorve73** [Apoorve73/racefor100.github.io#31]
- [x]  Add the Game Rules and workflow(as seen by the player). 
- [x] Add a GIF for the working of Game,

The app is purely static, so can easily be cloned and used. :)

**Comment by docs4opensource** [comment]
I'm organizing a documentation event for Hacktoberfest, and this looks like a good issue for some of our first-timers. Do you have the Game Rules someone could use to create the docs with? If so, someone from our event could take this on. [https://organize.mlh.io/participants/events/4451-hacktoberfest-documentation-meetup-kick-off-event](https://organize.mlh.io/participants/events/4451-hacktoberfest-documentation-meetup-kick-off-event)

**Comment by Apoorve73** [comment]
This will be really great @docs4opensource ! The game rules have been mentioned on the website itself. Find them here at https://apoorve73.github.io/racefor100.github.io/ . So feel free to check it. The same needs to be added in an elegant manner to the repo. 

Ask any queries, if you have any doubts. You can pass this on to someone from the event! :) 
All the best :+1:

**Comment by viveksahu26** [comment]
Hey @Apoorve73  , is this work open for first time user or new contributer. Then i would like to work on it..

**Comment by Apoorve73** [comment]
This is open for all! Do give a read to rules mentioned in README regarding "How to make your PR?" You can start working on this. If you pass the checks of BOT, then I will review that at my end.
