### ISSUE TITLE
Create an MIT LICENSE 

### ISSUE THREAD

**Issue by Apoorve73** [Apoorve73/racefor100.github.io#39]
Add MIT License to this repository.

**Comment by monizb** [comment]
Ill take this one

**Comment by Apoorve73** [comment]
Cool! Go ahead!

**Comment by Apoorve73** [comment]
I an extremely sorry @monizb , as a PR has already been made by @ruddha2001  and passed all the checks.
I am glad, you came forward to contribute to this project, and would like you to keep an eye on upcoming issues and work on it! :)
