### ISSUE TITLE
Sum is NaN Bug 

### ISSUE THREAD

**Issue by prasoonjain006** [Apoorve73/racefor100.github.io#4]
If we enter anything as a input, other than a **number**, it calculates the sum to be **NaN**, and after this it keeps showing the same, whatever may be our response.

**Comment by DevanshVarshney25** [comment]
I think it needs to be specified for only ‘number’ inputs.

**Comment by Apoorve73** [comment]
This is indeed a bad thing! :-| @prasoonjain006 Can you make the necessary changes? :-)

**Comment by prasoonjain006** [comment]
Working on it .  .

**Comment by Apoorve73** [comment]
Do pull the changes from master branch before making a pull request!

**Comment by prasoonjain006** [comment]
okay
