### ISSUE TITLE
Add Working Game's GIF

### ISSUE THREAD

**Issue by Apoorve73** [Apoorve73/racefor100.github.io#44]
Add A GIF for the Game's Working in the README.

**Comment by itsnitinr** [comment]
Hi, could I do it please?

**Comment by Apoorve73** [comment]
Sure thing @itsnitinr ! Go ahead! :space_invader:

**Comment by Gautam-Arora24** [comment]
Hey!!! Could I go ahead and solve this issue?

**Comment by Apoorve73** [comment]
Sorry @Gautam-Arora24 ! This issue is already resolved! I will look forward for more contributions from your side! :smiley:
