### ISSUE TITLE
Add Rounds to the Game

### ISSUE THREAD

**Issue by Apoorve73** [Apoorve73/racefor100.github.io#47]
# This is a feature request for this game.

## For now the player either wins or lose from Computer, but now it is required that :

- [x] Both the Player and Computer play 2 Rounds at once. 
- [x] If Computer Wins Both Rounds >> *Computer Wins*
- [x] If Player wins Two Rounds >> *Player Wins*
- [x] Else Tie

### Note
This can be done by setting up a loop that will run two times for a particular player, and will declare result after the two iterations are done, on the basis of above mentioned conditions.

**Comment by niteshseram** [comment]
@Apoorve73  I would love to work on this

**Comment by abhaybhatt** [comment]
@Apoorve73 can i work on this feature?

**Comment by Apoorve73** [comment]
@niteshseram @abhaybhatt The repository had been inactive for some time. But now it's again a part of Hacktoberfest under OSS Port. Please feel free to reply to this thread if you still want to take the issue.
Thanks
