### ISSUE TITLE
display scoreboard, prevent continous prompt

### ISSUE THREAD

**Issue by Apoorve73** [Apoorve73/racefor100.github.io#8]
For now, player gets a PROMPT, each time to enter a number and see the total sum. To make it more feasible, remove prompt and display three scoreboards each representing 
1. Number input by user, using button
2. Number guessed by computer
3. Total sum
respectively.
In order to prevent any changes in master branch, a new branch "**scoreboard_btn_input**".
Fork this branch and make changes accordingly!

**Comment by Apoorve73** [comment]
Follow this link to learn how to work on the desired branch other than master https://stackoverflow.com/questions/9227873/fork-from-a-branch-in-github

**Comment by Apoorve73** [comment]
Or if you are working with master, then submit the pull request for the above mentioned branch! Follow this link for more information on this. https://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github

**Comment by Apoorve73** [comment]
By mistake, this issue was mentioned in a recent pull request. This issue is still opened!

**Comment by prasoonjain006** [comment]
@Apoorve73  You want to display scoreboard in an **alert** box ?

**Comment by Apoorve73** [comment]
No, It has to be displayed as a part of the <div class="container">
